### PR TITLE
Update Access.md

### PR DESCRIPTION
**Pull request by PearlSexToy**

### CODE REVIEW

**Review by SilkieSabra — COMMENTED** [review]
This is not correct.  First you would not use the "menu" call to add an owner.  Second, the /1 is not at fault here.  Since there is a missing space in your example, I'm guessing you did not copy the string exactly and did something like /1addowner instead of /1 add owner.  In most cases, chat commands can be written either with or without space but in cases where a value is inserted (such as the owner key here) the spaces are critical.

**Review by SilkieSabra — COMMENTED** [review]
This is good practice for me at reviewing changes.  It looks like you are giving general advice that you needed yourself when trying this, because you did not grasp the concept of "call" as a placeholder and so were adding "menu" where it doesn't belong and where the guide does not specify it either.  A chat command consists of a prefix, a "call" which generates some action, and sometimes a parameter or value.  This is explained in the Prefixes and Chat Commands page in the guide.

**Comment by SilkieSabra** [comment]
I will not add a line to "not include menu" when doing add owner because the existing documentation nowhere says to do that.

**Comment by PearlSexToy** [comment]
Got it!!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Pull request closed without merging**
